# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Offline package operations for XeroLinux
# Only removes live ISO packages; no network access required
---
backend: pacman
skip_if_no_internet: false
update_db: false
update_system: false

pacman:
    num_retries: 3
    disable_download_timeout: true
    needed_only: true

operations:
  - remove:
    - ckbcomp
    - qt6-doc
    - live-launcher
    - qt6-examples
    - calamaresx-app
    - calamaresx-nv-cfg
    - memtest86+-efi
