modules-search: [ local ]

instances:
- id:       nonet
  module:   welcome
  config:   welcome-offline.conf
- id:       before
  module:   shellprocess
  config:   shellprocess-before.conf
- id:       final
  module:   shellprocess
  config:   shellprocess-final.conf
- id:       offline
  module:   packages
  config:   packages-offline.conf

sequence:
- show:
  - welcome@nonet
  - locale
  - keyboard
  - partition
  - usersq
  - summary

- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - luksbootkeyfile
  - luksopenswaphookcfg
  - shellprocess@before
  - initcpiocfg
  - initcpio
  - removeuser
  - usersq
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - packages@offline
  - grubcfg
  - bootloader
  - shellprocess@final
  - preservefiles
  - umount
- show:
  - finishedq

branding: XeroOFF

prompt-install: true

dont-chroot: false

oem-setup: false

disable-cancel: false

disable-cancel-during-exec: false

hide-back-and-next-during-exec: false

quit-at-end: false
